# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: WGD Society
email: warwickvgdsoc@googlemail.com
description: >- # this means to ignore newlines until "baseurl:"
  WGD Society is the Warwick campus home of game design, run by students, for students.
  We support all levels of skill and ambition, from first-timers looking for guidance,
  to full-fledged devs looking for a community or a team.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://warwick-game-design.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

logo: "/wgd-assets/lfs/common/warwick-name-logo.svg"
favicon_ico: "/wgd-assets/lfs/common/logo-greyborder.png"

# Build settings
theme: just-the-docs
color_scheme: wgd
plugins:
  - jekyll-feed

exclude:
  - "*.aux"
  - "*.blg"
  - "*.fls"
  - "*.out"
  - "*.bbl"
  - "*.fdb_latexmk"
  - "*.latexmkrc"
  - "wgd-assets/src/"
  - "wgd-assets/README.md"
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
